# Generated by Django 3.1.3 on 2021-07-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='santri',
            old_name='id_wali',
            new_name='nama_wali',
        ),
    ]
