# Generated by Django 3.1.3 on 2021-07-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0003_pengguna_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggaran', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Pelanggaran',
            },
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategory', models.CharField(blank=True, choices=[('Ringan', 'Ringan'), ('Sedang', 'Sedang'), ('Berat', 'Berat')], max_length=150)),
                ('kejadian', models.DateField()),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('nama_pelanggaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='santri.pelanggaran')),
                ('nama_santri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='santri.santri')),
            ],
            options={
                'verbose_name_plural': 'Laporan',
            },
        ),
    ]
