# Generated by Django 3.1.3 on 2021-07-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0004_laporan_pelanggaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggaran',
            name='nama_pelanggaran',
            field=models.CharField(max_length=200),
        ),
    ]
