# Generated by Django 3.1.3 on 2021-07-16 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0006_auto_20210716_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santri',
            name='nama_wali',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='santri.walisantri'),
        ),
        migrations.AlterField(
            model_name='santri',
            name='pendidikan',
            field=models.CharField(choices=[('UNIVERSITAS ZAINUL HASAN', 'UNIVERSITAS ZAINUL HASAN'), ('SMA Zainul Hasan', 'SMA Zainul Hasan'), ('MA Zainul Hasan', 'MA Zainul Hasan'), ('SMP Zainul Hasan', 'SMP Zainul Hasan'), ('MTS Zainul Hasan', 'MTS Zainul Hasan')], default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
