# Generated by Django 3.1.3 on 2021-07-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0007_auto_20210716_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='nama_pelanggaran',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Pelanggaran',
        ),
    ]
