# Generated by Django 3.1.3 on 2021-07-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0008_auto_20210716_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laporan',
            new_name='LaporanPelanggaran',
        ),
        migrations.AlterModelOptions(
            name='laporanpelanggaran',
            options={'verbose_name_plural': 'Laporan Pelanggaran'},
        ),
    ]
