# Generated by Django 3.1.3 on 2021-07-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0009_auto_20210716_2103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaporanPelanggaran',
            new_name='Pelanggaran',
        ),
    ]
