# Generated by Django 3.1.3 on 2021-07-17 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0011_walisantri_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggaran',
            name='santri',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
