# Generated by Django 3.1.3 on 2021-07-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0012_pelanggaran_santri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggaran',
            name='santri',
        ),
    ]
