# Generated by Django 3.1.3 on 2021-07-17 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0013_remove_pelanggaran_santri'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggaran',
            name='nama_wali',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='santri.walisantri'),
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='santri',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
