# Generated by Django 3.1.3 on 2021-07-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0015_auto_20210718_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='santri',
            old_name='nama_santri',
            new_name='nama',
        ),
    ]
