# Generated by Django 3.1.3 on 2021-07-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0017_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
