# Generated by Django 3.1.2 on 2021-08-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0018_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='walisantri',
            name='chat_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
