# Generated by Django 3.1.2 on 2021-08-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0020_auto_20210802_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santri',
            name='nama_wali',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wali_santris', to='santri.walisantri'),
        ),
    ]
