# Generated by Django 3.1.3 on 2021-08-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0022_auto_20210802_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggaran',
            name='Hukuman',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='santri',
            name='nama_wali',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='santri.walisantri'),
        ),
    ]
