# Generated by Django 3.1.3 on 2021-08-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0023_auto_20210804_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelanggaran',
            old_name='Hukuman',
            new_name='hukuman',
        ),
    ]
