# Generated by Django 3.1.3 on 2021-08-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0024_auto_20210804_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walisantri',
            name='user',
        ),
    ]
