# Generated by Django 3.1.3 on 2021-08-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santri', '0026_auto_20210814_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengurus',
            options={'verbose_name_plural': 'Pengurus'},
        ),
    ]
